### ISSUE TITLE
Lack of link to documentation preview

### ISSUE THREAD

**Issue by Czaki** [napari/docs#107]
The circle CI introduced in #104 works, but the job of posting the link to the documentation preview does not work. 

See, for example, https://github.com/napari/docs/pull/105

![obraz](https://user-images.githubusercontent.com/3826210/219621079-db550c7d-d3e4-4b06-88e3-24a21901ff44.png)

It should be fixed. Maybe @melissawm, you will have a fast idea of what is missed.

**Comment by psobolewskiPhD** [comment]
The actions tab shows the error with the redirector:
https://github.com/napari/docs/actions/runs/4202980264
`Input required and not supplied: repo-token`

**Comment by psobolewskiPhD** [comment]
The action has:
https://github.com/napari/docs/blob/e2103a394738f5a22b92e1e628ddeb439f42cacd/.github/workflows/circleci.yml#L20

But the action README:
https://github.com/larsoner/circleci-artifacts-redirector-action
shows
`           repo-token: ${{ secrets.GITHUB_TOKEN }}`

Edit: Maybe we need to add a secret: https://docs.github.com/en/actions/security-guides/encrypted-secrets

**Comment by melissawm** [comment]
Yes - the name of the token is not important, but we **do** need to add a new token. We discussed this at the documentation working group meeting, and @DragaDoncila mentioned that only @jni seems to have the permissions to do that, I am happy to help debug if it still doesn't work after that.

**Comment by psobolewskiPhD** [comment]
@melissawm I seem to have access to secrets in the Settings tab, but it's scary to think about touching anything there!

**Comment by Czaki** [comment]
> Yes - the name of the token is not important, but we **do** need to add a new token.

could you explain why? the `secrets.GITHUB_TOKEN` is the default one predefined by GitHub. What is the benefit of adding a new token?

**Comment by melissawm** [comment]
You need to create a token with public_repo authorization on the repository side for CircleCi to be able to write messages to the status of each PR. First, you need to [authorize CircleCI in your repo](https://circleci.com/docs/first-steps/), then you need to create the token to be able to use the [CircleCI redirect artifact action](https://github.com/larsoner/circleci-artifacts-redirector-action). I was hoping to discuss this before merging the other PR but it ended up being faster than I expected :smile:

**Comment by melissawm** [comment]
Now - I think your second question is why we need a *separate* token instead of using the existing one. I am not 100% sure here, but it seems to me like this is good security practice - if one of them gets compromised, for example, this wouldn't interfere with the other. But I am happy to be corrected here!

**Comment by Czaki** [comment]
> Now - I think your second question is why we need a _separate_ token instead of using the existing one. I am not 100% sure here, but it seems to me like this is good security practice - if one of them gets compromised, for example, this wouldn't interfere with the other. But I am happy to be corrected here!

In general, it is true, but `GITHUB_TOKEN` is a special one. GitHub provides the `GITHUB_TOKEN` with scope for a given repository. And GitHub could cycle it without contacts with maintainers.

Currently, GitHub provides "Fine-grained personal access tokens", but this is beta. And "Personal access tokens (classic)" is much more problematic as it allows one to perform almost any action that the creator can do. So usage of this token, when it was not needed, opens a security hole. 

I try to debug this on my fork but currently failing.

**Comment by melissawm** [comment]
ok - let me know what you find. Did you see this issue? https://github.com/larsoner/circleci-artifacts-redirector-action/issues/33

**Comment by Czaki** [comment]
You mean this? 

![obraz](https://user-images.githubusercontent.com/3826210/219758163-2fba079a-6d89-4eeb-b75a-3f65e34d3d9a.png)

**Comment by psobolewskiPhD** [comment]
Reading up a bit, I'm pretty confident that the settings on the repo are correct and we just need to change the name of the token used in the action to GITHUB_TOKEN.
Alternately, as @melissawm points out we could create a token with the matching name.
Alas, I don't think this can be tested with a PR. 
Basically, the change needs to be merged, then a PR updated with merge main.
I'd vote for the first option, because it's the simplest and matches the README of the action so easier for someone to understand in the future. (This is also what numpy/numpy has in theirs.)
