### ISSUE TITLE
Feature request: Add "matplotlib" image scraper for gallery

### ISSUE THREAD

**Issue by aganders3** [napari/docs#129]
## 🧰 Task
I'm working on a new gallery example for https://github.com/napari/napari/pull/5642, and it was suggested to add some images using `plt.imshow`. I tried this, but it didn't immediately work. Eventually I found that sphinx-gallery has configurable [image scrapers](https://sphinx-gallery.github.io/stable/configuration.html#image-scrapers). They offer a matplotlib scraper, and in fact it is on by default, but we change the configuration to use a qt scraper (overriding the default): https://github.com/napari/docs/blob/7f74c93a6b6040d6b19a35577419d981f069b33e/docs/conf.py#L223

Testing locally shows just adding `"matplotlib"` there works as I would expect. I just wanted to check if this was intentionally removed for some reason before I open a PR.

**Comment by psobolewskiPhD** [comment]
Should this be in the other repo? napari/docs?

**Comment by aganders3** [comment]
Isn't this napari/docs?

**Comment by psobolewskiPhD** [comment]
er...sorry 😣
