### ISSUE TITLE
DOC Document `imshow`

### ISSUE THREAD

**Issue by lucyleeow** [napari/docs#14]
## 📚 Documentation

With the merging of https://github.com/napari/napari/pull/4928 should we amend our documentation to introduce and use `imshow` instead of the `view_*` functions? Since there was suggestion of moving away from the `view_*` functions (https://github.com/napari/napari/pull/4928#issuecomment-1215983083) 

cc @jni

**Comment by jni** [comment]
Yup, huge +1 from me!

**Comment by psobolewskiPhD** [comment]
There is example usage in the quick start:
https://napari.org/stable/tutorials/fundamentals/getting_started.html?highlight=imshow#python-script-usage
and viewer tutorial:
https://napari.org/stable/tutorials/fundamentals/viewer.html?highlight=imshow#launching-the-viewer

So I'm going to close, though a PR to napari/napari with an imshow in an example could be nice...
