### ISSUE TITLE
Docs build failing (due to PyOpenGL?)

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/docs#163]
## 🐛 Bug

I just noticed that the docs build is failing on CI (https://github.com/napari/docs/actions/runs/5078127401/jobs/9122262373) when trying to render example scripts with napari. I saw a similar issue on napari-threedee and pinning `PyOpenGL < 3.1.7` fiixed the issue (https://github.com/napari-threedee/napari-threedee/pull/133). I haven't had a chance to dig in further. I'm not sure if this is something we pin here or if we need to do it in the core napari repo.

**Comment by kevinyamauchi** [comment]
cc @jni , I saw that you just tried to re-run the CI.

**Comment by Czaki** [comment]
why we have [build_docs.yml](https://github.com/napari/docs/blob/main/.github/workflows/build_docs.yml) and [deploy_docs.yml](https://github.com/napari/docs/blob/main/.github/workflows/deploy_docs.yml)? 

I have fixed build_docs.yml in #162, but I do not expect that we could have two workflows for same task

**Comment by kevinyamauchi** [comment]
Hmm good question. Sorry, @Czaki , but I do not know.

**Comment by Czaki** [comment]
The #164 will pin dependencies also in deploy_docs. We will need to handle the problem when update dependencies show in the main repository.

**Comment by melissawm** [comment]
build_docs was meant to run on PRs for previews, and deploy is supposed to run only after merging. Since we now have CircleCI for PR previews, I think we could go without build_docs.

**Comment by psobolewskiPhD** [comment]
Also, the deploy action is called from napari/napari, as far as i can tell.

**Comment by psobolewskiPhD** [comment]
PyOpenGl was updated the other day, so it fits the timeline of being responsible. I can't find any change log/release notes though 😢
