### ISSUE TITLE
CircleCI docs previews have errors

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/docs#166]
## 🐛 Bug

I'm seeing errors in the the CircleCI preview docs, see:
https://output.circle-artifacts.com/output/job/9bd40329-d940-4772-acbf-52cc1caa393a/artifacts/0/docs/_build/tutorials/fundamentals/viewer.html#toggle-ndisplay-2d-3d-button

But the build artifacts are fine, see: 
https://github.com/napari/docs/pull/159#issuecomment-1566246879

Looking at:
https://github.com/napari/docs/blob/main/.circleci/config.yml
I suspect the issue could be related to the previous CI errors, likely due to new `pyopengl` (3.1.7), because the constraints file (pinning 3.1.6) is not used on CircleCI:
https://github.com/napari/docs/blob/741829fdf90c06d0593baaa183a95f152e35bac4/.circleci/config.yml#L51

See:
https://app.circleci.com/pipelines/github/napari/docs/191/workflows/8dd09c09-6c46-4cd3-b69c-b944781c269c/jobs/181?invite=true#step-105-340

## Environment

https://app.circleci.com/pipelines/github/napari/docs/191/workflows/8dd09c09-6c46-4cd3-b69c-b944781c269c/jobs/181

## Additional context

See: https://github.com/napari/docs/pull/164

CC: @Czaki

**Comment by Czaki** [comment]
It was fixed in #162 and #164. It looksl like same patch should be used for circleci. It will be the third PR to fix the same thing (I think that same PR will apply main repository). Does Did we have any other place that we should patch?

**Comment by melissawm** [comment]
I believe this should be the last one, thanks @Czaki !
