### ISSUE TITLE
napari.types documents some imports

### ISSUE THREAD

**Issue by dstansby** [napari/docs#170]
## 🐛 Bug
[The docs for `napari.types`](https://napari.org/stable/api/napari.types.html#module-napari.types) include listings for standard library imports (e.g. `partial, `TypedDict`) that shouldn't be there. Solution is probably to add `__all__` to `types.py`. 

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by melissawm** [comment]
I am trying to look at a bunch of these. Currently, if you see the errors generated in the docs build, they include a lot of extra documentation from imported modules - especially for typing. I wonder how much of this we can include explicit intersphinx documentation for, instead of trying to document all of these. I'll take a look

**Comment by dstansby** [comment]
For this specific issue about the API reference pages, I think you only want to be documenting stuff that's directly defined in the module that's being documented anyway?

**Comment by melissawm** [comment]
For this specific case, napari/napari#5894 will change the napari.types documentation page from 

<img width="1345" alt="Screenshot 2023-06-01 at 4 05 57 PM" src="https://github.com/napari/docs/assets/3949932/b4ae177d-7afe-4448-a282-2ab94003f60d">

to 

<img width="1345" alt="Screenshot 2023-06-01 at 4 06 07 PM" src="https://github.com/napari/docs/assets/3949932/7548c0eb-1474-468c-9a63-6f2ebd36a840">

(note the sidebar contents).

Is this what we want?

**Comment by dstansby** [comment]
Yes, I think so. All the items not present in the second screenshot are imports, mainly from the Python standard library.
