### ISSUE TITLE
[Maintenance] Add concurrency and cancel-in-progress to PR workflow

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/docs#172]
## 🧰 Task

Every commit to a PR triggers the workflows which then queue up.
On napari/napari the `concurrency` feature was implemented to allow `cancel-in-progress`:
https://github.com/napari/napari/pull/4154/files
This should also be ported over to this repo for the PRs here, so that the artifact and CircleCI previews are generated only for the latest commits.

**Comment by Czaki** [comment]
I have enabled auto cancel redundant workflow in circleci settings 

![obraz](https://github.com/napari/docs/assets/3826210/224dfc48-4ced-4d73-a786-45cc27c3d9e8)

It looks like a solution for this Issue.

**Comment by psobolewskiPhD** [comment]
The build_docs workflow that makes the zip artifact also needs to auto-cancel.
