### ISSUE TITLE
Add logo to home page

### ISSUE THREAD

**Issue by dstansby** [napari/docs#188]
## 📚 New content request
The napari logo is so nice it seems a shame not to have it somewhere on the [docs home page](https://napari.org/stable/)!

**Comment by jni** [comment]
Not enough for you @dstansby??? 😜 

<img width="754" alt="Screenshot 2023-06-27 at 12 25 10 pm" src="https://github.com/napari/docs/assets/492549/a1fa92e2-4e0c-4d6b-b58e-c936f381e5c1">

In seriousness, 👍 to this.

**Comment by dstansby** [comment]
🤣

**Comment by melissawm** [comment]
How about the following mock-up: 
![Screenshot_20230627_113432](https://github.com/napari/docs/assets/3949932/c307d0c9-ab3a-4293-82f4-876dec93f7cf)

**Comment by jni** [comment]
@melissawm the size disparity between the logo and text is too big imho. Here's a few examples for inspiration:

![image](https://github.com/napari/docs/assets/492549/a1327e23-bfef-47e5-af7d-5edee14a0f26)
![image](https://github.com/napari/docs/assets/492549/18236593-4357-4c21-9c4b-7449779942a3)
![image](https://github.com/napari/docs/assets/492549/ff070937-6b91-42af-b66a-adc30fedc903)
![image](https://github.com/napari/docs/assets/492549/ae721c22-bd69-4866-b519-2dab0f9c4e80)

(Obviously sklearn and mpl are special cases but the point is that the graphic and text are roughly on the same scale.)

But probably this might also fall into the category of "let's go back to depending on pydata sphinx theme and then make improvements upstream if needed". eg I can imagine some config options for the theme like:

```
logo-in-navbar: path/to/logo.png
navbar-logo-height: 16pt
title-in-navbar: true
navbar-title-fontsize: 16pt
```

What do you think?

**Comment by melissawm** [comment]
How do we feel about the current logo? Is this still something we want to redesign?

**Comment by psobolewskiPhD** [comment]
I think it looks good now:
<img width="520" alt="image" src="https://github.com/user-attachments/assets/f315687a-cdb1-456c-8a88-ab6d3ea08dc0">
Unless the idea was to have it in the body where it says `napari: ...`? But i think for the current site design the current location is fine?

**Comment by dstansby** [comment]
Looks great to me!
