### ISSUE TITLE
Warn that first run of napari after install is slow (~30 s)

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/docs#222]
## 🧰 Task

In the various install/getting started docs we should warn the user that the first-run time is slow (>30 s for me) but that subsequent starts are markedly faster.
A user could think something went wrong with the install and cancel or restart terminal.

(This was feedback from the LatAm workshop on Aug. 7, 2023)

**Comment by brisvag** [comment]
Is this just on mac or everywhere? On my linux laptop, a new env with freshly installed napari took at most 5 secs to launch the first time, and about the same to launch the second time.

**Comment by Czaki** [comment]
@brisvag I meet this on Windows with AV and on Mac.
