### ISSUE TITLE
Build should fail if a new page is added but it's not in the TOC

### ISSUE THREAD

**Issue by jni** [napari/docs#227]
## 🧰 Task

In #144, a new page was added but it wasn't being built in the docs because it wasn't in the toc.yml. This is a very easy step to miss (I have done so many times). Ideally the build would fail if that's the case, or, if that's too hard (because for some reason sometimes we want pages not in the toc?), we could make a bot that warns when that happens? 🤷 Anyway, it would be good to not have to rely on understanding the build system to miss these things...

**Comment by melissawm** [comment]
OOps! This was closed in error and should still be checked out. To be clear, we are explicitly ignoring these errors because there are so many generated by the docs build (mostly involving autosummary).

**Comment by melissawm** [comment]
This now works 🎉
