### ISSUE TITLE
Incorrect formatting for manifest reference

### ISSUE THREAD

**Issue by DragaDoncila** [napari/docs#231]
## 🐛 Bug
The formatting for the [manifest reference](https://napari.org/dev/plugins/technical_references/manifest.html) falls apart after the `icon` field - I think it's because of double breaks in the paragraph or perhaps the bullet points? The rest of the table is then just formatted as text:

![image](https://github.com/napari/docs/assets/17995243/797b02f9-614e-4a85-874c-ef5cc7c82749)

## Environment

Present on 0.4.18 and stable docs (basically since the introduction of the `icon` field.

**Comment by melissawm** [comment]
This file comes directly from npe2, so I will submit a PR there to fix it.

**Comment by melissawm** [comment]
Duplicate of https://github.com/napari/npe2/issues/308

**Comment by lucyleeow** [comment]
Maybe we could close this as duplicate? I will copy the image to the other issue as I think it helps.

Just realised the other issue is in npe2, I guess it's worth having an issue in both repos...

**Comment by melissawm** [comment]
Closing as fixed - this is how the page looks now:

![Captura de imagem_20240926_180044](https://github.com/user-attachments/assets/09ca361d-fdd2-43e2-8193-b0400f3b66ee)
