### ISSUE TITLE
Update `magicgui` guide for `npe2`

### ISSUE THREAD

**Issue by DragaDoncila** [napari/docs#244]
## 🧰 Task
The "Using magicgui in napari plugin widgets" [guide](https://napari.org/stable/guides/magicgui.html#using-magicgui-in-napari-plugin-widgets) has lots of fantastic information, but unfortunately ends with totally outdated info about its use in plugin widgets. I think we should either remove that section entirely and just link to the plugin guides, or better yet, update it for `npe2`. We should also likely be linking to it from the widget contribution guide.

**Comment by psobolewskiPhD** [comment]
I think updating is the better way to go even at the cost of some duplications?
I'd like widgets to be documented as a thing independent of plugins.
So I think it would be good to surface this better.
`using magicgui in napari` doesn't really say what this guide is about, unless someone knows what magicgui is.
Maybe more like `Extending napari GUI with widgets`?

**Comment by lucyleeow** [comment]
> using magicgui in napari doesn't really say what this guide is about, unless someone knows what magicgui is.

Yes! I agree.

> I'd like widgets to be documented as a thing independent of plugins.

I agree that widgets are special but [Using magicgui in napari](https://napari.org/stable/guides/magicgui.html#using-magicgui-in-napari) already lives under `Usage` -> `In-depth explanation` (and not under `Plugins`). Would you add a "widget" section somewhere in `Usage`? Would you migrate any info from `Contribution Guides` -> [`Widgets`](https://napari.org/stable/plugins/guides.html#widgets)?

**Comment by lucyleeow** [comment]
Okay how about:

* Add more context to "Using magicgui in napari"
* Add to example of how to add the widget to viewer in a python script, similar to magicgui docs: https://pyapp-kit.github.io/magicgui/generated_examples/napari/napari_parameter_sweep/#code
* Move the "Using `magicgui` in napari plugin widgets" section under Plugins section (but add cross links)
    * The plugins -> Contribution Guide section can be re-organised in a follow up PR

> I'd like widgets to be documented as a thing independent of plugins.

Maybe under Usage there could be a widgets/extending GUI section that introduces widgets and how to add then via a python script. It can then link to plugins section if user wants to make a plugin out off their widget? The magicgui stuff would be a section here.

**Comment by DragaDoncila** [comment]
I like your proposal to split stuff up and crosslink @lucyleeow! In particular I like the idea of a more generic "extending GUI" section, where we can also talk about hooking up callbacks to events to achieve custom functionality

**Comment by DragaDoncila** [comment]
I gave a talk at Janelia at some stage about extending the napari GUI with not **just** plugins, gonna drop the [slides](https://docs.google.com/presentation/d/1sSpq60Qk9_CpkMKKSr72NQHjMcRGxF8kwus6mjUx0gM/edit?usp=sharing) here in case they're useful

**Comment by lucyleeow** [comment]
Ahhh the slides are great! Can't believe we haven't turned them into docs yet?!

**Comment by DragaDoncila** [comment]
Yeahh that's my bad 😅 to be honest I'd mostly forgot about it until I saw this issue

**Comment by psobolewskiPhD** [comment]
Ya! that's really a great resource!
Was there a recording?!?!

**Comment by DragaDoncila** [comment]
@psobolewskiPhD I'll follow up
