### ISSUE TITLE
DOC Proposal for achitecture documentation

### ISSUE THREAD

**Issue by lucyleeow** [napari/docs#25]
## 📚 Documentation
Related to https://github.com/napari/napari/issues/1426 but thought it would be better to start a new issue that would outline specifically what architecture docs could be added and potential people to get information from. Discussed in recent documentation [working group meeting](https://hackmd.io/10DKrIMhREmk9sa_QRirlg). Motivated partly by having a technical writer!

Not expert, please feel free to edit/comment. 

#### Architecture type docs that already exist

Most architecture type docs are in [In-depth explanations](https://napari.org/dev/guides/index.html).

* [Using magicgui in napari](https://napari.org/dev/guides/magicgui.html) - how to use magicgui to compose GUIs. Also useful for plugin writers.
* [Asynchronous rendering](https://napari.org/dev/guides/rendering.html) - talks about Octree implementation and rendering, some information architecture but usage information as well.
* [An introduction to the event loop in napari](https://napari.org/dev/guides/event_loop.html) - talks about the `QtEventLoop` - how actions taken by user result in 'events' (functions) added to the queue. User information here as well. Note this is distinct from napari python model events (defined by `Event`, `EventEmitter`, and `EmitterGroup`) see: https://github.com/lucyleeow/napari/pull/7#discussion_r921482283 for more.
* [Hooking up your own events](https://napari.org/dev/howtos/connecting_events.html) - I think this is aimed at plugin writers (?). Talks about how to connect user events (e.g., keypress, mouse events) to functions.
* [Napari models and events](https://napari.org/dev/guides/napari_models.html) - talks about how the 3 main components of napari (python models, qt classes and vispy classes) are connected.
* [Contexts and expressions](https://napari.org/dev/guides/contexts_expressions.html) - also useful for writing plugin manifests
* [App-model](https://napari.org/dev/guides/app_model.html) - app-model provides framework for the declarative schema that napari will be moving to. Describes how to compose the various registries.

Plugin docs
* [Your First Plugin](https://napari.org/dev/plugins/first_plugin.html) - introduces writing your own plugin and minimum requirements. Introduces the plugin cookiecutter.
* [Manifest Reference](https://napari.org/dev/plugins/manifest.html) - introduces manifest and details fields
* [Contributions Reference](https://napari.org/dev/plugins/contributions.html) - introduces contributions and details fields
* [Contribution Guides](https://napari.org/dev/plugins/guides.html) - more detailed guide on all contribution types except `commands` and `themes`
* [Test and Deploy](https://napari.org/dev/plugins/test_deploy.html) - some tips for testing and release and deployment guide
* [Best practices](https://napari.org/dev/plugins/best_practices.html) - best practices. Has a section on tests and coverage - would this be better in the 'Test and Deploy' section?
* [npe2 migration guide](https://napari.org/dev/plugins/npe2_migration_guide.html) - how to migrate old 'npe1' plugins to npe2 plugin

#### New architecture docs and layout

A lot of useful information is contained in existing docs listed above but better organisation of the docs and context could be useful. In particular, information could be thought to target 3 groups of people: plugin devs, napari devs and users. It would be nice if we could have sections targeting each group. I understand there will be some overlap between groups and topic areas where it makes more sense to keep information on the whole topic in one section, but this could probably be resolved by cross-linking.

Potential outline (again not well versed in napari, suggestions welcome):

* **Broad overview of contents/structure of `napari/` folder and affiliated packages** - e.g., tests live alongside code in `_test/` folder, layer model objects describing image data live in `napari/layers`. High level intro to affiliated packages e.g., npe2, app-model.
* **Napari dev info**:
  * How data is handled - information about how e.g., the layer classes, `LayerList`, camera class etc work
  * How the GUI/widgets are created and work - e.g., how `_QtMainWindow` and `ViewerModel` works, including existing docs: [Using magicgui in napari](https://napari.org/dev/guides/magicgui.html) and [App-model](https://napari.org/dev/guides/app_model.html)
  * Information about rendering - how rendering, the canvas, `VispyBaseLayer` etc works. Maybe some information about async rendering?
  * How components are connected - information about how changing something in GUI or console results in changes to the viewer events, the `QtEventLoop` and existing docs: [Napari models and events](https://napari.org/dev/guides/napari_models.html), [An introduction to the event loop in napari](https://napari.org/dev/guides/event_loop.html), [Hooking up your own events](https://napari.org/dev/howtos/connecting_events.html), [Contexts and expressions](https://napari.org/dev/guides/contexts_expressions.html).
* **Plugin dev info**: the current plugin documentation is pretty good but could do with some improvements
  * maybe introduce the history of npe1 and npe2 earlier?
  * add an outline page that details the docs and cross references relevant pages (e.g., 'extending napari' section)
  * would a section in 'Contribution Guides' about `commands` with examples be useful?
  * mention the testing utilities provided in the cookiecutter, in the 'Test and Deploy' section
  * mention the guide in the readme of the cookiecutter
* **User info**: useful user info currently contained in [In-depth explanations](https://napari.org/dev/guides/index.html) could be moved to other appropriate places so they do not live with dev/architecture docs. Adding an 'Extending napari' section would be nice (see: https://github.com/napari/docs/issues/25). This could include things like 'How to connect functions to events'.

**Other stuff**
I recall that we have some vendored code (from qt or vispy..?), maybe some background information about this would be useful. Maybe dev targeted info on how (multi)threading works?

cc @DragaDoncila @chili-chiu

**Comment by chili-chiu** [comment]
thanks @lucyleeow!
tagging @Nadalyn-CZI here :)

**Comment by Nadalyn-CZI** [comment]
Thanks.

**Comment by DragaDoncila** [comment]
@lucyleeow I really like this proposed outline, and thanks for the detailed summary of what's currently out there. In general I'm a fan of the separation of concerns between 'developing napari' and 'developing with napari' info, but I don't think we should label stuff like "hooking up your own events" or even magicgui as strictly for plugin developers.

We definitely want to encourage people writing their own custom workflows in notebooks/scripts even if they're never going to build a plugin out of it. For that reason I think we should consider the overarching categories 'developing napari' and maybe 'extending napari'? 

> How to add menu items/keybindings - related to App-model

Some of this stuff iirc is documented 'automatically' through `npe2` - certainly the contributions reference is autogenerated, but the contributions guides may not be? Regardless we'll want to make sure the new docs for menu contributions follow the same pattern.

**Comment by lucyleeow** [comment]
> thanks for the detailed summary of what's currently out there.

I am conscious I may have missed something though so please let me know.

> overarching categories 'developing napari' and maybe 'extending napari'

Sounds good. Just to clarify, what kind of information do you see in each?


> Some of this stuff iirc is documented 'automatically' through npe2 

Ah yes I forgot. It would be nice to have one central place to go to for documentation on writing plugins but I guess cross-referencing will do. WDYT?

**Comment by lucyleeow** [comment]
I'm going to close this as the docs have changed a bit since I wrote this and I think it is out of date now.
