### ISSUE TITLE
Docs build is failing

### ISSUE THREAD

**Issue by melissawm** [napari/docs#259]
## 🐛 Bug

We're getting a 

```
Extension error:
Could not import extension sphinx_tags (exception: cannot import name 'get_matching_files' from 'sphinx.util.matching' (/home/circleci/project/venv/lib/python3.10/site-packages/sphinx/util/matching.py))
make: *** [Makefile:30: docs-build] Error 2
```

See, for example, https://app.circleci.com/pipelines/github/napari/docs/365/workflows/73b5e766-7082-4c2f-9774-dffa61a364e6/jobs/355?invite=true#step-107-2326_16

I will try to take a look.

**Comment by psobolewskiPhD** [comment]
I noticed it in the other PR:
https://github.com/napari/docs/pull/256#issuecomment-1786315010
It's due to a new sphinx_tags release 👀  That import requires sphinx >5.1

**Comment by psobolewskiPhD** [comment]
It passes with sphinx 5.3 (lifted pin to <6), oddly it works even without the same change in the sphinx-theme

**Comment by Czaki** [comment]
yes, but it should be guarded by a constraints file.

**Comment by melissawm** [comment]
https://github.com/napari/docs/pull/256#issuecomment-1787195520 

cc @jni
