### ISSUE TITLE
Uniform circleci workflow with main repository

### ISSUE THREAD

**Issue by Czaki** [napari/docs#261]
## 🧰 Task

In the context of the fail spotted in #259 I found that circleci workflow between the main repository and this repository differs. 

I think that we should find a way to uniform it for simplifaction of maintenance.

**Comment by Czaki** [comment]
We may investigate orbs for this: 

https://circleci.com/docs/orb-concepts/
https://circleci.com/docs/reusing-config/

**Comment by Czaki** [comment]
Short summary. 
Circle ci does not allow just passing paths to a YAML file (like in GitHub reusable workflows). It requires adding an orb to some form of register, and the orb needs to live in a separate repository. 

So, the advantage of using Orb is that we could have a single source of truth that should require one PR to fix docs built in both repositories. The disadvantage is the next repository to maintain. 

Another option is to create a build docs script (improve makefile, for example). The advantage is that it does not add a separate repository. It still has a single PR to fix most of the problems. The disadvantage is that the main changes, like the change of the Python version, will still require two PRs and the log will be less readable. 

The third option is just to synchronize `.circle/config.yml` to represent the same structure.

**Comment by psobolewskiPhD** [comment]
I think I'd vote for option 3. We can put a reminder in the comments in both files that if you PR one to do the other. I can't imagine these workflows needing that much regular maintenance anyways.

Edit: oops, mis-clicked close. sorry!

**Comment by melissawm** [comment]
I can see the appeal of automating this but I do fear it will be one more script to maintain anyway. So I'd vote for option 3 as well. We could add someone as a code owner on the actions (I'd be happy to be pinged for that, or maybe one of the core devs) to make sure they are pinged whenever there are changes that need to be synced.
