### ISSUE TITLE
Viewer documentation assumes interactive terminal

### ISSUE THREAD

**Issue by stefanv** [napari/docs#27]
The [viewer documentation](https://napari.org/tutorials/fundamentals/viewer.html) assumes you are not writing code in a Python file, and therefore does not add `.show()` to the napari viewer. Some text explaining that this is necessary outside an interactive, matplotlib-aware context would be helpful.

**Comment by tlambert03** [comment]
Thanks @stefanv, very good point.

the API is subtly different from matplotlib here though (and nothing is matplotlib-aware here, it just uses `%gui qt` from IPython if available). Technically the viewer _widget_ is "visible/shown" by default (what we need here is the event loop if we're outside of IPython).   So, to the docs, we would add `napari.run()` to the end of teh script, as shown in the majority of our [examples](https://github.com/napari/napari/tree/main/examples)

(or, if you want to block the progression of the script), `viewer.show(block=True)` should work too.

anyway, definitely should be made clearer in the docs.

**Comment by stefanv** [comment]
Yes, of course---event loop, not matplotlib, sorry!  And `block=True` was what I ended up with, but `run` would probably be more suitable for the docs.

**Comment by psobolewskiPhD** [comment]
The recent rework of the viewer tutorial (https://github.com/napari/docs/pull/65) now starts with:
<img width="789" alt="image" src="https://user-images.githubusercontent.com/76622105/228586668-5b2d1336-0fe4-40a5-8e01-f382db9e9362.png">

I think this addresses this issue?
