### ISSUE TITLE
update dask docs to use map blocks

### ISSUE THREAD

**Issue by alisterburt** [napari/docs#28]
The napari tutorial for [using dask for lazy loading/processing](https://napari.org/tutorials/applications/dask.html) uses `da.stack()` on a list of delayed readers, `da.map_blocks()` is (according to @tlambert03 this morning) a better way to achieve this so we should update the docs to reflect that

**Comment by GenevieveBuckley** [comment]
This issue is related to (and possibly a duplicate of) https://github.com/napari/docs/issues/30

**Comment by melissawm** [comment]
Closing as a duplicate of #30 - I have moved this suggestion over there.
