### ISSUE TITLE
Reorganise 'Contributing guide'

### ISSUE THREAD

**Issue by lucyleeow** [napari/docs#281]
## 🧰 Task

Proposal to reorganise [Contributing guide](https://napari.org/dev/developers/contributing.html):

```
Contributing guide
|-- How to contribute                          # Reorganise of current contributing guide page
|   |-- Setting up a development installation   
|   |-- Opening a Pull Request  
|   |-- Adding tests
|   |-- Translations
|   |-- Adding an icon  
|   `-- Performance
|   |   |-- Benchmarks
|   |   `-- Profiling
|   `-- Contributing documentation 
`-- Napari architecture guide
    |-- Directory structure                   # To be added in new PR
    |-- An introduction to the event loop     # Migrate from 'In-depth explanations'
    |-- Napari models and events              # Migrate from 'In-depth explanations'
    `-- App-model                             # Migrate from 'In-depth explanations'

```

* 'How to contribute' would include an index
* The pages to migrate from 'In-depth explanations' are really aimed at devs, and state this at the start of the docs. For "An introduction to the event loop" only the section after 'in depth' will be migrated.

Related #25, this would be a small step towards improving napari architecture docs. The reorganisation would be in one PR and the "Directory structure" section would be a separate PR.

**Comment by lucyleeow** [comment]
@DragaDoncila the "Directory structure" section would include info about the Qt separation of files and how we attempt to mirror file structure.

also cc  @melissawm

**Comment by lucyleeow** [comment]
Maybe there could be a 'Repo guide' section (re: #191) that could be linked to from the landing page?

**Comment by melissawm** [comment]
Love these ideas @lucyleeow ! Please let me know if I can help with any pieces of it 😄

**Comment by DragaDoncila** [comment]
Love it! Especially having some kind of section started on architecture. I can't remember exactly what's in those guides about events but if there's anything about how to hook up your own events, we should split those out and keep them in `Usage`

**Comment by Czaki** [comment]
Why `|   |-- Adding a theme`? I do not expect new theme bundled with napari (Should I?). Maybe `Modify theme`?

**Comment by lucyleeow** [comment]
Ahhh, yeah I am not familiar with themes. [Creating and testing themes](https://napari.org/dev/developers/contributing.html#creating-and-testing-themes) is currently in the [Contributing guide](https://napari.org/dev/developers/contributing.html#contributing-guide) page, but from what you are saying, this doc would actually fall under usage?

(I amended, but the all sections under "How to contribute" are just a reorganise of the current 'contributing guide' page)

**Comment by lucyleeow** [comment]
Honestly a lot of our docs need more context. It should say, for your own install of napari, you can change the theme...

**Comment by Czaki** [comment]
We now allow to contribute themes as plugins. So maybe we should move this section to plugin docs?

**Comment by lucyleeow** [comment]
Well maybe we could put it in usage because users can make their own theme without contributing it as a plugin. It is also not a 'standard' plugin contribution. But we can add a link to it in the plugins section?

**Comment by lucyleeow** [comment]
Note I've updated the structure to place 'contributing documentation' under 'How to contribute' in an attempt to highlight doc contributions are as important as code contributions.
