### ISSUE TITLE
Use same workflow for `build_docs` and `build-and-deploy`

### ISSUE THREAD

**Issue by lucyleeow** [napari/docs#284]
## 🧰 Task

Could we use the same workflow to build docs in `build_docs` and `build-and-deploy` and only do the deploy step on:
```
    tags:
      - 'v*'
```
see: https://github.com/napari/docs/issues/283#issuecomment-1837618199

This means we do not have to remember to keep the 2 workflows consistent.

I am not an expert on github workflows, would this be possible @melissawm ?

**Comment by melissawm** [comment]
+1 from me, I am happy to put in a PR for that if there is consensus 😄

**Comment by lucyleeow** [comment]
I think @psobolewskiPhD and @Czaki are both +1 on this too :grimacing:

**Comment by lucyleeow** [comment]
I think this would reduce maintenance burden!
