### ISSUE TITLE
Problem screenshots in "Using magicgui in napari" in dev

### ISSUE THREAD

**Issue by lucyleeow** [napari/docs#285]
## 🐛 Bug

The screenshots in "Using magicgui in napari" in [dev](https://napari.org/dev/guides/magicgui.html#using-magicgui-in-napari) look squished:

![image](https://github.com/napari/docs/assets/23182829/191ed7be-949b-47ad-a654-f0bbef2b1981)

on [stable](https://napari.org/stable/guides/magicgui.html#using-magicgui-in-napari) the same screenshot:

![image](https://github.com/napari/docs/assets/23182829/ffdf3fd5-4720-48e6-9d13-96fca9ce8ef4)

Note this is the worst example, the others on the page look better but still squished compared to stable.

Could it be related to https://github.com/napari/docs/pull/207 @aganders3  ?

**Comment by lucyleeow** [comment]
Actually on the same page under "Updating an existing Layer" there is a screenshot in [stable](https://napari.org/stable/guides/magicgui.html#updating-an-existing-layer) but in [dev](https://napari.org/dev/guides/magicgui.html#updating-an-existing-layer) there isn't even a screenshot ?

**Comment by aganders3** [comment]
This feels less like it would be related to #207 than the other one, but I'll still try to take a look at both today.

**Comment by lucyleeow** [comment]
You're totally right, that was a brain fart on my end. And maybe there was a change to myst nb

**Comment by lucyleeow** [comment]
Related: #283

**Comment by psobolewskiPhD** [comment]
These also appear to be fine in the CircleCI render:
https://output.circle-artifacts.com/output/job/a6aac828-d441-45bc-871d-c0ae279fd1f2/artifacts/0/docs/docs/_build/guides/magicgui.html
(this link is from latest merge to docs main)
But the zip artifact (GH runners build_docs) for #290 (https://github.com/napari/docs/actions/runs/7093485902)
has the same issue. 
However, when I build locally they are fine.
So this seems to be a manifestation of the same issue as #283

**Comment by lucyleeow** [comment]
> So this seems to be a manifestation of the same issue as https://github.com/napari/docs/issues/283

Thanks @psobolewskiPhD, I'll keep this open just for the documentation but hopefully the same fix will resolve both.

**Comment by psobolewskiPhD** [comment]
Fixed by https://github.com/napari/docs/pull/294
