### ISSUE TITLE
Add link to GUI examples in 'Creating widgets' page

### ISSUE THREAD

**Issue by lucyleeow** [napari/docs#293]
## 🧰 Task

There are some good widget examples in the gallery, under GUI tag. We could add a link to these in the "Creating widgets" page.

Relies on #286 and https://github.com/melissawm/sphinx-tags/issues/85 being merged :grimacing: !

**Comment by psobolewskiPhD** [comment]
I think that you covered this here:
https://github.com/napari/docs/pull/286/files/6c7414e7e5daba3705ba960db9e2138956245caa#diff-b1906dec29c918ce9702c2ccd915f4213296ad8e1e39ff1e3e5938ba17dd2b35R40-R41

Or do you mean we should make a new `widget` tag?

**Comment by lucyleeow** [comment]
I meant instead of linking to the URL (which is what I did in #286), link via a reference label (which you can't do atm because sphinx tags does not add a reference label to tag indexes).

I realised after I created this issue that I can just use the URL, which is less robust than a reference label but it works :shrug: 

Since it is linked I will close this!
