### ISSUE TITLE
Do not use path cross-references

### ISSUE THREAD

**Issue by lucyleeow** [napari/docs#296]
## 🧰 Task

We have cross references using paths (relative and absolute)  to files, e.g.,:

https://github.com/napari/docs/blob/0c7029e5c9674e9d56c5efbec1022fa302661280/docs/community/index.md?plain=1#L13

This breaks if we re-organise our directory structure. Could we use [explicit targets](https://myst-parser.readthedocs.io/en/latest/syntax/cross-referencing.html#creating-explicit-targets) instead?

This would make it easier if we re-organise our docs (e.g., https://github.com/napari/docs/issues/282) or make changes as we update our API etc.

**Comment by lucyleeow** [comment]
cc @melissawm WDYT ?

**Comment by psobolewskiPhD** [comment]
I'm in favor, we've run into this before. Not sure there's a good way to mass implement this. First need to add targets to everything (e.g. that dev/index doesn't have one) and then fix the links. And then add an explanation to the docs contribution guide.

**Comment by melissawm** [comment]
Sounds good to me!

**Comment by lucyleeow** [comment]
Yeah I am not sure there is a way to automate this. Let me have a go at doing it by hand :grimacing:

**Comment by lucyleeow** [comment]
I think this can be closed now, I've done most of it and the remaining I don't think needs to be done. Thanks all!
