### ISSUE TITLE
[dev, latest] Links on Community > Team page go back to stable.

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/docs#331]
## 🐛 Bug
The first two links here:
https://napari.org/dev/community/team.html
to the Governance model switch the version of the site to Stable.

I think this should be considered a bug, because out-dated information could be shown.

**Comment by melissawm** [comment]
That is strange! I'll take a look.

**Comment by psobolewskiPhD** [comment]
Holy no-line-breaks batman! 🤯 
https://github.com/napari/docs/blob/512e78becf1b1e47981f92192988fa7752a09dcb/docs/community/team.md?plain=1#L3
The links are hard-coded rather than using the markdown.

**Comment by melissawm** [comment]
And that's why we should always use anchors rather than direct links 😁
