### ISSUE TITLE
Add Community calendar to a more prominent location (homepage?)

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/docs#353]
## 🧰 Task
Brought up at the NA/EU meeting today: the calendar with meetings is not prominent, so may be hard for community to even know that there are meetings.
We should put it in a tile on the homepage or in some other more prominent location.

**Comment by melissawm** [comment]
I am thinking of a few options here.

- Option 1: adding a link through the index page, in the text itself. Note that this would require people to read the index page to find the info.

- Option 2: something like the following:
![Screenshot_20240226_191938](https://github.com/napari/docs/assets/3949932/7e3527c5-6849-431c-a408-f22f7871cf3f)

- Option 3: including a sidebar to the landing page:
![Screenshot_20240226_193730](https://github.com/napari/docs/assets/3949932/a375cdc5-77ea-44b4-8285-24df21d58260)

**Comment by brisvag** [comment]
We already have a sidebar for the `search`, so I'd use all that blank space for something.

**Comment by Czaki** [comment]
I prefer the second option
