### ISSUE TITLE
[API] the API docs for napari.utils.nbscreenshot are empty

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/docs#376]
## 🐛 Bug
`napari.utils.nbscreenshot` is in the API docs, but it's actually an alias to NotebookScreenshot
There is no documentation for nbscreenshot:
https://napari.org/stable/api/napari.utils.nbscreenshot.html
![image](https://github.com/napari/docs/assets/76622105/a6144d1c-125c-4571-a8b5-810505e217ee)

Meanwhile NotebookScreenshot has a very nice and helpful doctstring, complete with example:
https://github.com/napari/napari/blob/705c30768cbed43ea3d8a0cad4af1b6f1190fbc2/napari/utils/notebook_display.py#L20-L49

## Environment

stable (0.4.19) and latest

**Comment by psobolewskiPhD** [comment]
Hmm, is the solution to add NotebookScreenshot import to the __init__?
https://github.com/napari/napari/blob/705c30768cbed43ea3d8a0cad4af1b6f1190fbc2/napari/utils/__init__.py#L11-L22

cc: @melissawm

**Comment by melissawm** [comment]
Let me take a look - this is probably not the only instance of this kind of missing content
