### ISSUE TITLE
Latest build_deploy workflow deleted `dev` on deploy to gh-pages

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/docs#383]
## 🐛 Bug
napari.org latest is a 404 because `dev/` is deleted
https://github.com/napari/napari.github.io/commit/3a3d212877d16cb90e0b6c5376aaa8e20bd38d25

While the commit is a different PR, it's because of concurrency--two PR merged at the same time basically.
The issue lies with the workflow edited here:
https://github.com/napari/docs/pull/380
Could also be the tags issue raised during review of https://github.com/napari/docs/pull/348

**Comment by DragaDoncila** [comment]
Noooo I'm sorry! :cry: That's what I get for merging in a repo I haven't been fully keeping upwith. What's the solution here - can we manually deploy just to get them back up?

**Comment by lucyleeow** [comment]
Even stable looks weird, but maybe thats just me?

![image](https://github.com/napari/docs/assets/23182829/d7436069-3101-4e1a-9a1f-ce2842dd66ae)

**Comment by psobolewskiPhD** [comment]
Hmm I think stable was using something from dev -- the version switcher and the announcement?
So with dev being deleted, that could explain it.
I think I have a fix...
https://github.com/napari/docs/pull/384

**Comment by psobolewskiPhD** [comment]
Not your fault at all @DragaDoncila 
There was an error in the original workflow that I tried to fix, but obviously failed. 
It just looks like your merge is odd, but that's because the merge just before the actions were canceled.
