### ISSUE TITLE
app-model intersphinx link is broken

### ISSUE THREAD

**Issue by melissawm** [napari/docs#387]
## 🐛 Bug
The URL for the app-model objects.inv file seems to be invalid. When building the docs, I get:

```
WARNING: falha ao alcançar todos os inventários com os seguintes problemas:
intersphinx inventory 'https://app-model--142.org.readthedocs.build/en/142/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://app-model--142.org.readthedocs.build/en/142/objects.inv
```

Indeed the base url https://app-model--142.org.readthedocs.build/en/142 does not seem correct, but I also can't find the correct location of the objects.inv file. I can only find https://app-model.readthedocs.org/

**Comment by psobolewskiPhD** [comment]
Looks like they're here:
http://app-model.readthedocs.io/en/latest/objects.inv
