### ISSUE TITLE
Add info on how plugin docs from npe2 are deployed

### ISSUE THREAD

**Issue by lucyleeow** [napari/docs#391]
`docs_deployment.md` is very useful but we don't have info on how the plugin docs from npe2 are deployed.

@melissawm do you know how it works?

**Comment by melissawm** [comment]
Yes - there is a little note here about this: https://napari.org/dev/developers/contributing/documentation/index.html#organization-of-the-documentation

The actual building of the autogenerated .md files is done in https://github.com/napari/docs/blob/main/docs/_scripts/prep_docs.py

I can add a better description in the contributing documentation guide 👍🏻
