### ISSUE TITLE
Match `napari` install in CircleCI and GitHub actions doc build

### ISSUE THREAD

**Issue by lucyleeow** [napari/docs#398]
Circle CI installs:

https://github.com/napari/docs/blob/1c6155fd6e2f9dd053559bef73bb5f04bda5878c/.circleci/config.yml#L35

GitHub Actions:

https://github.com/napari/docs/blob/1c6155fd6e2f9dd053559bef73bb5f04bda5878c/.github/workflows/build_and_deploy.yml#L50

**Comment by lucyleeow** [comment]
Noticed in #396

**Comment by psobolewskiPhD** [comment]
There's a lot of discussion/comparison here too: https://github.com/napari/docs/issues/283

**Comment by lucyleeow** [comment]
Good point. I realise there is #305 and the install is related to whether PySide/PyQt. I'll close this and comment on #305
