### ISSUE TITLE
Document `napari --reset` as a way to reset settings to default (and solve problems)

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/docs#40]
## 🧰 Task

Changing napari versions—or conda envs with different napari versions—can cause issues with settings. Also, things like Full Screen or no-menu or 2nd display can cause napari to be hard to interact with. These issues can be solved by resetting the settings back to default using the terminal command: `napari --reset`
This command is not documented in the user facing docs.

**Comment by melissawm** [comment]
Could this fit into an existing documentation page (like the [viewer tutorial](https://napari.org/stable/tutorials/fundamentals/viewer.html))?

**Comment by psobolewskiPhD** [comment]
@melissawm I'm not sure, maybe? I think one issue is that Preferences and setting keybinds are not well covered by the user facing docs, see https://github.com/napari/docs/issues/13
So it's not clear where to provide this.
There also isn't any sort of *Troubleshooting* or FAQ section, so yeah, maybe the viewer tutorial is the best place at the moment?
