### ISSUE TITLE
Question: How to document arm64-native installation on macOS? (aka Apple Silicon, M1, M2)

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/docs#43]
## 🧰 Task

napari has been fully functional on arm64 macOS (aka Apple Silicon, M1, M2) for over a year... 
...but it should probably be still considered experimental. 
Still, more and more people are getting the new macs...
The main issue is that there is no Qt5 wheel on pypi (pyqt5, pyside2), so the "batteries included" install [all] doesn't work. (If they arn't available now, they will never be available?)
So there are two options:
1. For Qt5, one needs to make a conda env and install `pyqt` from conda-forge then `pip install napari` will work—or just install napari from conda-forge (the later is in the docs, but not specified as for arm64 macOS)
2. Or one can go exponential on experimental and install Qt6 (pyqt6 or pyside6) from pypi, then napari installs fine without conda, but it's experimental.

(BTW, same goes for dev environments. Also, one can use `pamba`: https://github.com/tlambert03/pamba )

The other option is to promote x86 envs and Rosetta2 emulation. This works fine for most non-intensive things, but fails once tensorflow is involved (and probably other similar high-performance libraries).

I'm not sure what the best path forward is, but I think we're close to a critical mass that something needs to be put forth.

Aside: the only other big thing not on pypi I've run into (other than Qt5 that is) is `imagecodecs` it's on conda-forge. If anyone has bandwidth to help me help @Czaki with https://github.com/Czaki/imagecodecs_build please let me know.

**Comment by melissawm** [comment]
Could anyone with an Apple Silicon machine take notes on what they need to install napari? Doesn't have to be super organized, but with that info I could come up with the content around it. Unfortunately I don't have access to a Silicon machine to do it myself.

**Comment by psobolewskiPhD** [comment]
I have an M1 🤣 
It's more a question of what we want to support on the arm64 side.
For example, this line:
`napari can be installed on most macOS, Linux, and Windows systems with Python 3.8-3.10 using pip:`
which starts the `batteries included` install section, is not wrong: it says `most` and it will work on Apple Silicon envs run in emulation. But that install will fail on native arm64 python envs. Is it enough to say that there? That `pip install napari[all]` is just for x86 (and emulated) python on macOS?

Next, the existing conda install instructions work perfectly on both arm64-native and emulation environments on Apple Silicon. So maybe we don't need to add anything, but they also don't say that they will work, so someone looking for how to install may not get it.

But what if someone wants to clone and `pip install -e .` then conda doesn't help them. Which is when they'd need to get `pyqt` from conda-forge and then `pip install`. But this is rather unorthodox and maybe for a more advanced user?

**Comment by Czaki** [comment]
My previous work on imagecodecs wheel was very time-consuming. Maybe there are some places where I could apply for a grant (like napari plugin acceleration grants) to support such a job? 

The current workflow is built on tape and saliva, so every improvement is time consuming. But rewriting it is not fast.

**Comment by jaimergp** [comment]
@Czaki - maybe a [NumFOCUS Small Development Grant](https://numfocus.org/programs/small-development-grants)?

**Comment by Czaki** [comment]
I will try to trace when the next funding rounds will be available.
