### ISSUE TITLE
Add a Getting more help page under Usage

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/docs#66]
## 📚 New content request

There is a section Help on the main napari.org:
https://napari.org/stable/index.html#help
But it's pretty far down and I can imagine someone missing it.
Perhaps in the Usage ToC there could be a `Getting help` page?

This is related to PR: https://github.com/napari/napari/pull/5399
which aims to populate the Help menu of napari with some more helpful content.
A link to a `Getting help` page would be a natural fit.

### Outline

The `Getting help` page would more or less include the existing info at
https://napari.org/stable/index.html#help so it would mention:
image.sc as a place to post questions
GitHub issues as a place to post bug reports or problems
but I would also add a section about the napari zulip which is an awesome resource.

### Alternative

Just (or maybe *also*) add info about the napari zulip to https://napari.org/stable/index.html#help

**Comment by melissawm** [comment]
In the docs WG meeting we thought this can be closed with a note in the "Community" card of the landing page mentioning getting help.
