### ISSUE TITLE
Updating napari's Bundled App Installation Instructions

### ISSUE THREAD

**Issue by melissawm** [napari/docs#67]
This is a follow up to napari/napari#4383. Please see the discussion there.

**Comment by psobolewskiPhD** [comment]
As noted in the PR discussion, I think this is really important.
I would argue that we need a top top level tab (like Usage, Community, Plugins) for Installation. Then the Getting started, etc. guides and tutorials could focus on Usage.

**Comment by jaimergp** [comment]
I can work on this!

**Comment by jaimergp** [comment]
@psobolewskiPhD can I get this assigned? I cannot self-assign on this repo 😬

**Comment by psobolewskiPhD** [comment]
@jaimergp you got it! Let me know if I can help!

**Comment by jaimergp** [comment]
Opened https://github.com/napari/docs/pull/74 for now. Let's see if my git fu is good enough :D
