### ISSUE TITLE
Meta: Pin this repo to organization landing page?

### ISSUE THREAD

**Issue by melissawm** [napari/docs#91]
## 🧰 Task

Currently, the pinned repos for the napari org are as follows:

<img width="968" alt="Screenshot 2023-01-17 at 9 23 57 AM" src="https://user-images.githubusercontent.com/3949932/212898277-19d2c096-c214-40b4-bfd1-6fc9abd9ede7.png">

It could improve discoverability to have the docs repo pinned there as well.

**Comment by brisvag** [comment]
Yup, agree!

**Comment by psobolewskiPhD** [comment]
Ditto! 
Who do we need to ping for that? It needs to be an owner, so I guess @jni or @sofroniewn ?

**Comment by jni** [comment]
Done! 🚀

**Comment by psobolewskiPhD** [comment]
SO much nicer:
<img width="787" alt="image" src="https://user-images.githubusercontent.com/76622105/212909461-aff45745-f1ac-47a3-aa01-a07187ebc5c7.png">

🙏

**Comment by jni** [comment]
Actually I moved docs now, so it's now

napari  | docs
cookiecutter | npe2

wasn't sure about the order of the bottom two, but seems ok to me.
