### ISSUE TITLE
Feature request: PR comments with build preview website link

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/docs#98]
## 🧰 Task

PR comment with docs build preview ala numpy:
https://github.com/numpy/numpy.org/pull/596#issuecomment-1236103657
they use netlify: https://docs.netlify.com/site-deploys/notifications/#github-pull-request-comments

Looks like vercel also has something similar:
https://vercel.com/docs/concepts/deployments/comments/integrations

I'm not clear on the strengths and weaknesses of these, but it would be a **super** nice feature.
Disclaimer: my personal site is hosted by netlify.

**Comment by melissawm** [comment]
Oh that is different though. For the numpy.org website we do use netlify but that's not for the documentation. The documentation site uses [Circle CI](https://github.com/numpy/numpy/blob/main/.circleci/config.yml). I proposed this for napari, and unfortunately I can't find the discussion anymore, but the preference was for using github actions. Unfortunately there are several issues with that workflow that I haven't come around to fixing yet. 

Related:
- https://github.com/napari/napari/issues/3572
- https://github.com/napari/napari/issues/5055
- https://github.com/napari/napari/pull/5014
- https://github.com/napari/napari/pull/5148

**Comment by psobolewskiPhD** [comment]
The thing I like about the numpy thing is that it gives a link to just open the preview website in the browser, rather than downloading (another) docs.zip, unpacking, etc.
My internet is pretty slow, so downloading the docs.zip is a few minutes...

**Comment by melissawm** [comment]
Circle CI also does that - include a link to a live preview of the docs. Here's an example:

https://output.circle-artifacts.com/output/job/1630c903-f0d1-48be-980f-59962ec0d254/artifacts/0/doc/build/html/index.html

This comes from https://github.com/numpy/numpy/pull/23092

See the entry point here
![Screenshot_2023-01-28-08-29-36-345-edit_com android chrome](https://user-images.githubusercontent.com/3949932/215264222-400b7adc-01db-4384-bd8a-fe59166c3f87.jpg)

**Comment by psobolewskiPhD** [comment]
That PR is closed, but I went to another numpy/numpy one and I can't figure out where to see the build docs from the PR. 
The CicleCI `details` page, which seems the same as the one you put in the red box, doesn't show anything I can understand:
https://app.circleci.com/pipelines/github/numpy/numpy/17776/workflows/80b03de5-2ee0-4e74-b964-0815f6f63814/jobs/29828/steps

So by comparison the user experience with a comment and a simple link to the web preview as here https://github.com/numpy/numpy.org/pull/596#issuecomment-1236103657 
is much easier to use. 
I think this is especially important for this repo where we may get less advanced contributors and all of the PRs are likely to affect things user facing on the web site. In contrast to napari/napari PR docs building, where we're talking about API stuff from docstrings, right? So not as user facing.

**Comment by melissawm** [comment]
Well, I think something was wrong there, usually we do have the link to the artifacts - see https://github.com/numpy/numpy/pull/23073 and https://output.circle-artifacts.com/output/job/01284f19-57e2-4a0c-b561-8f4bea4b0c41/artifacts/0/doc/build/html/index.html

But point taken :) I can definitely check netlify. One issue I have faced previously is that they only allowed for one user to be the "owner" or administrator of the netlify instance for the website and this was a bit annoying on other projects. But I can investigate

**Comment by psobolewskiPhD** [comment]
Ok, yea that one you linked works! It's still not as obvious, but definitely better than what I saw.
Also, I'm not pushing netlify or anything! It just worked really nice in the numpy repo.
If the circleCI thing is easier, we can definitely try that and it's still a marked improvement (at least for me) over downloading a zip via clicking the Actions at the bottom.

**Comment by jni** [comment]
I just saw the circleCI thing in action in a skimage PR recently and it's 🏅 . imho it's better than a comment, as the comments can get pretty noisy. And if we go for the updating comment, then it becomes less obvious again than the build action link. So 👍 for the circleCI solution.

**Comment by psobolewskiPhD** [comment]
Fair enough! Just need to document it in the PR template maybe or via a first-time-PR-contributor action 👀

**Comment by melissawm** [comment]
I can do that!

**Comment by psobolewskiPhD** [comment]
FYI, we had some discussion about such an action in the core dev zulip, with mixed reactions, because I liked this post from the ITK folks
https://forum.image.sc/t/welcome-and-guide-first-time-contributors-with-a-github-action/75875
Anyhow, there was some support if it's used to convey info and I think non-obvious stuff like the circleCI click would be a good fit.

**Comment by melissawm** [comment]
Another example: https://github.com/matplotlib/matplotlib/pull/25122#pullrequestreview-1278395156

> Thank you for opening your first PR into Matplotlib!
> 
> If you have not heard from us in a while, please feel free to ping @matplotlib/developers or anyone who has commented on the PR. Most of our reviewers are volunteers and sometimes things fall through the cracks.
> 
> You can also join us [on gitter](https://gitter.im/matplotlib/matplotlib) for real-time discussion.
> 
> For details on testing, writing docs, and our review process, please see [the developer guide](https://matplotlib.org/devdocs/devel/index.html)
> 
> We strive to be a welcoming and open project. Please follow our [Code of Conduct](https://github.com/matplotlib/matplotlib/blob/main/CODE_OF_CONDUCT.md?rgh-link-date=2023-02-01T03%3A51%3A21Z).

**Comment by psobolewskiPhD** [comment]
Yeah, I think something like that but with also
1. a point about what will happen next—I know, many people will be experts even if first time napari, but still some may be first-time PR ever
2. a mention of the tests/actions? It's not super obvious. Here we could say the circleCI can show you a webpage preview of the docs.

**Comment by melissawm** [comment]
Here's a summary of what is needed here based on these comments:

- [x] Enable CircleCI for building docs
- [x] Document it in the PR template
- [x] Add note about it in the "how to contribute documentation" pages.

Separately, I've created another issue for the welcome-bot https://github.com/napari/napari/issues/5551

**Comment by psobolewskiPhD** [comment]
Sounds good to me!
I'd love to help with what I can!
❤️
